# force virtualbox provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "public_network", type: "dhcp", auto_correct:true
  config.vm.synced_folder "../../", "/projects"
  config.ssh.forward_agent = true
end
