# force virtualbox provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "../../", "/projects"
  config.ssh.forward_agent = true
end